tests: Fix (getcwd) failing without chroot
In case chroot and unshare are not available, $test_directory
remains the current directory. When the directory gets removed
(line 119) `guix pack` online 121 fails due to unsuccessful call
to '(getcwd)'.

--8<---------------cut here---------------start------------->8---
Backtrace:
In ice-9/boot-9.scm:
  1755:12  5 (with-exception-handler _ _ #:unwind? _ #:unwind-for-type _)
In unknown file:
           4 (apply-smob/0 #<thunk 7f38afd14300>)
In ice-9/boot-9.scm:
    724:2  3 (call-with-prompt ("prompt") #<procedure 7f38afd26be0 at ice-9/eval.scm:330:13 ()> #<procedure default-prompt-handler (k proc)>)
In ice-9/eval.scm:
    619:8  2 (_ #(#(#<directory (guile-user) 7f38afd17c80>)))
In ice-9/command-line.scm:
   193:24  1 (load/lang "/home/steelman/src/debian/guix/guix/scripts/guix")
In unknown file:
           0 (getcwd)

ERROR: In procedure getcwd:
In procedure getcwd: No such file or directory
--8<---------------cut here---------------end--------------->8---

There seem to be no reason not to switch back current directory
when not testing chroot and unsahre.

Fixes: 272c0709 ("tests: Add tests for "guix pack".")
Fixes: 92a0e60a ("pack: Adjust shell tests to read-only tarball root.")
Change-Id: Ib02bf3714f0c6706b5e759dbb28cf86edf0f1317