build-system/pyproject: Remove setup.py test backend.
The 'test' command was removed in setuptools>=72; remove the
corresponding test backend since it no longer works and causes the
'check' phase to fail with:

    usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
       or: setup.py --help [cmd1 cmd2 ...]
       or: setup.py --help-commands
       or: setup.py cmd --help

    error: invalid command 'test'

* guix/build/pyproject-build-system (check): Remove setup.py test backend.

Link: https://github.com/pypa/setuptools/issues/4519
Change-Id: I74ba3ae84732a8f913722c5213e3ccb3ab369ec3